version: "3"

services:
  web-server:
    build:
      context: .
    environment:
      - REALM=${REALM}
      - CLIENT_ID=${CLIENT_ID}
      - CLIENT_SECRET=${CLIENT_SECRET}
    ports:
      - "80:80"
      - "8080:8080"
      - "9200:9200"
